### ISSUE TITLE
Python3 `Shell.execute_command()` appends `b` to output

### ISSUE THREAD

**Issue by azjps** [bucknerns/sshaolin#11]
MRE:

```
from sshaolin.client import SSHClient
client = SSHClient(..)
shell = client.create_shell()
shell.execute_command("echo foo").stdout  # returns b'foo\nb'
```

The extra `b` comes because
```
# sshaolin/common.py
 273         @common.SSHLogger
 274         def execute_command(
 278             uuid = uuid4().hex.encode()
 279             cmd = "echo {1}\n{0}\necho {1} $?\n".format(cmd.strip(), uuid).encode()
```
will create a command in python3 like
```
b"echo b'8dc06c1eae334bab822480e7b9cffe21'\necho foo\necho b'8dc06c1eae334bab822480e7b9cffe21' $?\n"
```
and the extra `b` prefix will get read in as part of the returned output. There's plenty of ways to fix this, for example replacing `.format(.., uuid)` with `.format(.., six.ensure_str(uuid))`.

**Comment by bucknerns** [comment]
I stored uuid as a string and moved the .encode to where the sub function is called. That should fix this.
